
-- Create the tech_companies database
CREATE DATABASE IF NOT EXISTS tech_companies_db;

-- Use the tech_companies database
USE tech_companies_db;

-- Create the tech_companies data table
CREATE TABLE IF NOT EXISTS tech_companies_data (
    Ranking INT PRIMARY KEY,
    Company VARCHAR(255),
    Market_Cap FLOAT,
    Stock VARCHAR(10),
    Country VARCHAR(100),
    Sector VARCHAR(100),
    Industry VARCHAR(255)
);

-- Insert data into tech_companies_data table
-- Below is an example of how to insert data (to be generated by your data loading process)
INSERT INTO tech_companies_data 
(Ranking, Company, Market_Cap, Stock, Country, Sector, Industry)
VALUES
(1, 'Apple Inc.', 2866000000000, 'AAPL', 'United States', 'Technology', 'Consumer Electronics'),
(2, 'Microsoft Corporation', 2755000000000, 'MSFT', 'United States', 'Technology', 'Software—Infrastructure');

-- Example query to retrieve data
SELECT * FROM tech_companies_data;
